name: CI
on:
  push:
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
        - x86-windows
        - aarch64-macos
        - arm-linux-gnueabihf
        - wasm32-freestanding
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 2024.11.0-mach
        mirror: 'https://pkg.machengine.org/zig'
    - name: Build
      run: zig build -Dtarget=${{ matrix.target }}
    - if: ${{ matrix.target != 'wasm32-freestanding' }}
      name: Build Vulkan
      run: zig build -Dtarget=${{ matrix.target }}
      working-directory: example/vulkan
